<?php

namespace ContainerBvXTAy1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LXi7gqJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LXi7gqJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LXi7gqJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
            'teacher' => ['privates', '.errored..service_locator.LXi7gqJ.App\\Entity\\Teacher', NULL, 'Cannot autowire service ".service_locator.LXi7gqJ": it needs an instance of "App\\Entity\\Teacher" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repository' => 'App\\Repository\\TeacherRepository',
            'teacher' => 'App\\Entity\\Teacher',
        ]);
    }
}
