<?php

namespace ContainerBvXTAy1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UisV4OqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UisV4Oq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UisV4Oq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\TeacherRepository',
        ]);
    }
}
