<?php

namespace ContainerBvXTAy1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ovs_GCWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ovs.GCW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ovs.GCW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\LessonRepository', 'getLessonRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\LessonRepository',
        ]);
    }
}
