<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPh55GBM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPh55GBM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPh55GBM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPh55GBM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPh55GBM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ph55GBM',
    'container.build_id' => '9b34fd76',
    'container.build_time' => 1678180653,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPh55GBM');
