<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFSRWZiE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFSRWZiE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFSRWZiE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFSRWZiE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFSRWZiE\App_KernelDevDebugContainer([
    'container.build_hash' => 'FSRWZiE',
    'container.build_id' => '5f5e5edc',
    'container.build_time' => 1678267460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFSRWZiE');
