<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9zSdqxA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9zSdqxA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9zSdqxA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9zSdqxA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9zSdqxA\App_KernelDevDebugContainer([
    'container.build_hash' => '9zSdqxA',
    'container.build_id' => '12535124',
    'container.build_time' => 1678270231,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9zSdqxA');
