<?php

namespace ContainerFSRWZiE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D9pHme0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D9pHme0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D9pHme0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rvRepository' => ['privates', 'App\\Repository\\ReviewRepository', 'getReviewRepositoryService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'rvRepository' => 'App\\Repository\\ReviewRepository',
            'validator' => '?',
        ]);
    }
}
